#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get PHP version.
#======================================================================================================================

cd /tmp

PHP_VERSION=$(cat PHP_BUILD)
bf-echo "PHP version ${PHP_VERSION}."


#======================================================================================================================
# Install PHP dependencies.
#======================================================================================================================

bf-echo "Installing installation dependencies..."
apk add --no-cache --virtual .install \
    git
bf-done

bf-echo "Installing required PHP modules for v${PHP_VERSION}..."
apk add --no-cache \
    php82=${PHP_VERSION} \
    php82-ctype=${PHP_VERSION} \
    php82-curl=${PHP_VERSION} \
    php82-dom=${PHP_VERSION} \
    php82-fileinfo=${PHP_VERSION} \
    php82-gmp=${PHP_VERSION} \
    php82-iconv=${PHP_VERSION} \
    php82-intl=${PHP_VERSION} \
    php82-mbstring=${PHP_VERSION} \
    php82-opcache=${PHP_VERSION} \
    php82-pdo_mysql=${PHP_VERSION} \
    php82-pdo_sqlite=${PHP_VERSION} \
    php82-pdo_pgsql=${PHP_VERSION} \
    php82-phar=${PHP_VERSION} \
    php82-session=${PHP_VERSION} \
    php82-simplexml=${PHP_VERSION} \
    php82-tokenizer=${PHP_VERSION} \
    php82-xml=${PHP_VERSION} \
    php82-xmlreader=${PHP_VERSION} \
    php82-xmlwriter=${PHP_VERSION} \
    php82-zip=${PHP_VERSION}
bf-done


#======================================================================================================================
# Get FreeScout environment variables.
#======================================================================================================================

SRC=/etc/bf/src
bf-echo "Source directory: ${SRC}."

FRESHRSS=freshrss
FRESHRSS_SRC=${SRC}/${FRESHRSS}
bf-echo "FreshRSS source directory: ${FRESHRSS_SRC}."

FRESHRSS_VERSION=$(cat FRESHRSS_REVISION)
bf-echo "FreshRSS version ${FRESHRSS_VERSION}."


#======================================================================================================================
# Download and install FreshRSS.
#======================================================================================================================

bf-echo "Cloning FreshRSS v${FRESHRSS_VERSION} into ${FRESHRSS_SRC}"
git clone --depth 1 --branch ${FRESHRSS_VERSION} https://github.com/FreshRSS/FreshRSS ${FRESHRSS_SRC}
bf-done


#======================================================================================================================
# Set permissions on source files.
#======================================================================================================================

bf-echo "Setting permissions on ${FRESHRSS_SRC}..."
bf-ch -o www:www -m 0755 -t d ${FRESHRSS_SRC}
bf-ch -o www:www -m 0644 -t f ${FRESHRSS_SRC}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Removing /www files."
rm -f /www/*

bf-echo "Removing installation dependencies."
apk del .install
