#!/bin/bash

set -euo pipefail


#======================================================================================================================
# If an existing installation was detected, do not proceed.
#======================================================================================================================

if [ "${FRESHRSS_INSTALLED-}" = "1" ] ; then
    bf-echo "Existing installation detected - do not reinstall." "freshrss/setup-install"
    exit 0
fi


#======================================================================================================================
# Ensure all required environment variables are set.
#======================================================================================================================

[[ -z "${FRESHRSS_USER_NAME-}" ]] && bf-error "FRESHRSS_USER_NAME must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_USER_PASS-}" ]] && bf-error "FRESHRSS_USER_PASS must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_BASE_URL-}" ]] && bf-error "FRESHRSS_BASE_URL must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_DB_HOST-}" ]] && bf-error "FRESHRSS_DB_HOST must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_DB_USER-}" ]] && bf-error "FRESHRSS_DB_USER must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_DB_PASS-}" ]] && bf-error "FRESHRSS_DB_PASS must be set." "freshrss/setup-install"
[[ -z "${FRESHRSS_DB_NAME-}" ]] && bf-error "FRESHRSS_DB_NAME must be set." "freshrss/setup-install"


#======================================================================================================================
# Use CLI to run automated installation.
#======================================================================================================================

bf-echo "Installing FreshRSS..." "freshrss/setup-install"
cd "${FRESHRSS_CLI}"

# ensure all the needed directories are in /data
bf-echo " .. preparing ${FRESHRSS_DATA}" "freshrss/setup-install"
php ./prepare.php

# do install
bf-echo " .. installing database" "freshrss/setup-install"
php ./do-install.php \
    --default_user "${FRESHRSS_USER_NAME}" \
    --base_url "${FRESHRSS_BASE_URL}" \
    --db-type "mysql" \
    --db-host "${FRESHRSS_DB_HOST}" \
    --db-user "${FRESHRSS_DB_USER}" \
    --db-password "${FRESHRSS_DB_PASS}" \
    --db-base "${FRESHRSS_DB_NAME}" \
    --db-prefix "fr_"

# create user
bf-echo " .. creating user" "freshrss/setup-install"
php ./create-user.php \
    --user "${FRESHRSS_USER_NAME}" \
    --password "${FRESHRSS_USER_PASS}"
php ./actualize-user.php \
    --user "${FRESHRSS_USER_NAME}"

# disable updates
bf-echo " .. disabling updates" "freshrss/setup-install"
php ./reconfigure.php \
    --disable_update "true"
bf-done "freshrss/setup-install"
