#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Create /data symlink.
#======================================================================================================================

if [ ! -L ${FRESHRSS_DATA_SRC} ] ; then

    bf-echo "Deleting ${FRESHRSS_DATA_SRC} and recreating it as a symlink..." "freshrss/setup-data"
    rm -rf ${FRESHRSS_DATA_SRC}
    ln -s ${FRESHRSS_DATA} ${FRESHRSS_DATA_SRC}
    bf-done "freshrss/setup-data"

fi


#======================================================================================================================
# If a valid config file exist, mark the installation as complete.
#======================================================================================================================

[[ -f "${FRESHRSS_CONFIG}" ]] && bf-env "FRESHRSS_INSTALLED" "1" "freshrss/setup-data"
