#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

FRESHRSS_SRC=${BF_SRC}/freshrss
bf-env "FRESHRSS_SRC" "${FRESHRSS_SRC}"
bf-env "NGINX_ROOT" "${FRESHRSS_SRC}/p"
